export const ASTILLEROS = [
  'Antago',
  'Aqualum',
  'Arco Iris Eclipse',
  'Avalon',
  'Baader',
  'Bahamas',
  'Bayliner',
  'Beneteau',
  'Bermuda',
  'Boston Whaler',
  'Campanilli',
  'Canestrari',
  'Chris Craft',
  'Cranchi',
  'Custon',
  'Extreme',
  'Fairline',
  'Fórmula',
  'Four Winns',
  'Fuentes',
  'Geuna',
  'Hardcraft',
  'Jeanneau',
  'Kawasaki',
  'Kiel',
  'Klase A',
  'Luthom',
  'Malibu',
  'Mar y Rio',
  'Marine Sur',
  'Mastercraft',
  'Mediterranean',
  'Naval Center',
  'Naval Motor',
  'Pagliettini',
  'Pandora',
  'Piccini',
  'Preveza',
  'Princess',
  'Prinz',
  'Quest',
  'Quicksilver',
  'Ragazza',
  'Redacci',
  'Regal',
  'Regnicoli',
  'Riviera Yachts',
  'Roy',
  'Santana',
  'Sea Doo',
  'Sea Ray',
  'Segue',
  'Silver Boats',
  'SK',
  'Sky Nautique',
  'Sky Wake',
  'Tango Boats',
  'Tarrab',
  'Tracker',
  'Trento',
  'Ventura',
  'Visión',
  'Wellcraft',
  'Yamaha',
  'Zodiac Nautic',
] as const;
